// Generated by gencpp from file can/e2o_status.msg
// DO NOT EDIT!


#ifndef CAN_MESSAGE_E2O_STATUS_H
#define CAN_MESSAGE_E2O_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can
{
template <class ContainerAllocator>
struct e2o_status_
{
  typedef e2o_status_<ContainerAllocator> Type;

  e2o_status_()
    : velocity(0)
    , throttle(0)
    , brake(0)
    , steering(0)
    , steering_direc(0)
    , header()  {
    }
  e2o_status_(const ContainerAllocator& _alloc)
    : velocity(0)
    , throttle(0)
    , brake(0)
    , steering(0)
    , steering_direc(0)
    , header(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _velocity_type;
  _velocity_type velocity;

   typedef int32_t _throttle_type;
  _throttle_type throttle;

   typedef int32_t _brake_type;
  _brake_type brake;

   typedef int32_t _steering_type;
  _steering_type steering;

   typedef int32_t _steering_direc_type;
  _steering_direc_type steering_direc;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;





  typedef boost::shared_ptr< ::can::e2o_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can::e2o_status_<ContainerAllocator> const> ConstPtr;

}; // struct e2o_status_

typedef ::can::e2o_status_<std::allocator<void> > e2o_status;

typedef boost::shared_ptr< ::can::e2o_status > e2o_statusPtr;
typedef boost::shared_ptr< ::can::e2o_status const> e2o_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can::e2o_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can::e2o_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'can': ['/home/deepak/catkin_ws/src/can/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can::e2o_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can::e2o_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can::e2o_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can::e2o_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can::e2o_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can::e2o_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can::e2o_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94b6373a082ac03fa17612f6941ccfa8";
  }

  static const char* value(const ::can::e2o_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94b6373a082ac03fULL;
  static const uint64_t static_value2 = 0xa17612f6941ccfa8ULL;
};

template<class ContainerAllocator>
struct DataType< ::can::e2o_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can/e2o_status";
  }

  static const char* value(const ::can::e2o_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can::e2o_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 velocity\n\
int32 throttle\n\
int32 brake\n\
int32 steering\n\
int32 steering_direc\n\
std_msgs/Header header\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::can::e2o_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can::e2o_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.throttle);
      stream.next(m.brake);
      stream.next(m.steering);
      stream.next(m.steering_direc);
      stream.next(m.header);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct e2o_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can::e2o_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can::e2o_status_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.velocity);
    s << indent << "throttle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.throttle);
    s << indent << "brake: ";
    Printer<int32_t>::stream(s, indent + "  ", v.brake);
    s << indent << "steering: ";
    Printer<int32_t>::stream(s, indent + "  ", v.steering);
    s << indent << "steering_direc: ";
    Printer<int32_t>::stream(s, indent + "  ", v.steering_direc);
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MESSAGE_E2O_STATUS_H
