// Generated by gencpp from file pixhwk_ctrl_node/desired_velocity.msg
// DO NOT EDIT!


#ifndef PIXHWK_CTRL_NODE_MESSAGE_DESIRED_VELOCITY_H
#define PIXHWK_CTRL_NODE_MESSAGE_DESIRED_VELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pixhwk_ctrl_node
{
template <class ContainerAllocator>
struct desired_velocity_
{
  typedef desired_velocity_<ContainerAllocator> Type;

  desired_velocity_()
    : velocity(0.0)
    , priority(0)
    , node_id(0)  {
    }
  desired_velocity_(const ContainerAllocator& _alloc)
    : velocity(0.0)
    , priority(0)
    , node_id(0)  {
  (void)_alloc;
    }



   typedef double _velocity_type;
  _velocity_type velocity;

   typedef int8_t _priority_type;
  _priority_type priority;

   typedef int8_t _node_id_type;
  _node_id_type node_id;





  typedef boost::shared_ptr< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> const> ConstPtr;

}; // struct desired_velocity_

typedef ::pixhwk_ctrl_node::desired_velocity_<std::allocator<void> > desired_velocity;

typedef boost::shared_ptr< ::pixhwk_ctrl_node::desired_velocity > desired_velocityPtr;
typedef boost::shared_ptr< ::pixhwk_ctrl_node::desired_velocity const> desired_velocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pixhwk_ctrl_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pixhwk_ctrl_node': ['/home/deepak/catkin_ws/src/PixHawkController/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e42d3ef493b1319a15d2180a4aa66278";
  }

  static const char* value(const ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe42d3ef493b1319aULL;
  static const uint64_t static_value2 = 0x15d2180a4aa66278ULL;
};

template<class ContainerAllocator>
struct DataType< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pixhwk_ctrl_node/desired_velocity";
  }

  static const char* value(const ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 velocity\n\
				# 100 = edge_case(must be handled first);\n\
				# 99 - 51 = less than edge, more than traffic;	\n\
				# 49 - 2 = less than traffic, more than traj.\n\
int8 priority\n\
int8 node_id\n\
";
  }

  static const char* value(const ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.priority);
      stream.next(m.node_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct desired_velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pixhwk_ctrl_node::desired_velocity_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "priority: ";
    Printer<int8_t>::stream(s, indent + "  ", v.priority);
    s << indent << "node_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.node_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIXHWK_CTRL_NODE_MESSAGE_DESIRED_VELOCITY_H
