// Generated by gencpp from file pixhwk_ctrl_node/OmplStatus.msg
// DO NOT EDIT!


#ifndef PIXHWK_CTRL_NODE_MESSAGE_OMPLSTATUS_H
#define PIXHWK_CTRL_NODE_MESSAGE_OMPLSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pixhwk_ctrl_node
{
template <class ContainerAllocator>
struct OmplStatus_
{
  typedef OmplStatus_<ContainerAllocator> Type;

  OmplStatus_()
    : OmplSolStatus(0)
    , actualmsg()
    , stamp()  {
    }
  OmplStatus_(const ContainerAllocator& _alloc)
    : OmplSolStatus(0)
    , actualmsg(_alloc)
    , stamp()  {
  (void)_alloc;
    }



   typedef int8_t _OmplSolStatus_type;
  _OmplSolStatus_type OmplSolStatus;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _actualmsg_type;
  _actualmsg_type actualmsg;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> const> ConstPtr;

}; // struct OmplStatus_

typedef ::pixhwk_ctrl_node::OmplStatus_<std::allocator<void> > OmplStatus;

typedef boost::shared_ptr< ::pixhwk_ctrl_node::OmplStatus > OmplStatusPtr;
typedef boost::shared_ptr< ::pixhwk_ctrl_node::OmplStatus const> OmplStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pixhwk_ctrl_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pixhwk_ctrl_node': ['/home/deepak/catkin_ws/src/PixHawkController/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e50e9584b597fecb0c7c001901c2ff9";
  }

  static const char* value(const ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e50e9584b597fecULL;
  static const uint64_t static_value2 = 0xb0c7c001901c2ff9ULL;
};

template<class ContainerAllocator>
struct DataType< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pixhwk_ctrl_node/OmplStatus";
  }

  static const char* value(const ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 OmplSolStatus\n\
string actualmsg\n\
time stamp\n\
";
  }

  static const char* value(const ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.OmplSolStatus);
      stream.next(m.actualmsg);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OmplStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pixhwk_ctrl_node::OmplStatus_<ContainerAllocator>& v)
  {
    s << indent << "OmplSolStatus: ";
    Printer<int8_t>::stream(s, indent + "  ", v.OmplSolStatus);
    s << indent << "actualmsg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.actualmsg);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIXHWK_CTRL_NODE_MESSAGE_OMPLSTATUS_H
