// Generated by gencpp from file pixhwk_ctrl_node/PixHawk_SteeringControl.msg
// DO NOT EDIT!


#ifndef PIXHWK_CTRL_NODE_MESSAGE_PIXHAWK_STEERINGCONTROL_H
#define PIXHWK_CTRL_NODE_MESSAGE_PIXHAWK_STEERINGCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pixhwk_ctrl_node
{
template <class ContainerAllocator>
struct PixHawk_SteeringControl_
{
  typedef PixHawk_SteeringControl_<ContainerAllocator> Type;

  PixHawk_SteeringControl_()
    : steering(0.0)  {
    }
  PixHawk_SteeringControl_(const ContainerAllocator& _alloc)
    : steering(0.0)  {
  (void)_alloc;
    }



   typedef double _steering_type;
  _steering_type steering;





  typedef boost::shared_ptr< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> const> ConstPtr;

}; // struct PixHawk_SteeringControl_

typedef ::pixhwk_ctrl_node::PixHawk_SteeringControl_<std::allocator<void> > PixHawk_SteeringControl;

typedef boost::shared_ptr< ::pixhwk_ctrl_node::PixHawk_SteeringControl > PixHawk_SteeringControlPtr;
typedef boost::shared_ptr< ::pixhwk_ctrl_node::PixHawk_SteeringControl const> PixHawk_SteeringControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pixhwk_ctrl_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pixhwk_ctrl_node': ['/home/deepak/catkin_ws/src/PixHawkController/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13be5889908f58ce029441890e49203c";
  }

  static const char* value(const ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13be5889908f58ceULL;
  static const uint64_t static_value2 = 0x029441890e49203cULL;
};

template<class ContainerAllocator>
struct DataType< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pixhwk_ctrl_node/PixHawk_SteeringControl";
  }

  static const char* value(const ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 steering\n\
";
  }

  static const char* value(const ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PixHawk_SteeringControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pixhwk_ctrl_node::PixHawk_SteeringControl_<ContainerAllocator>& v)
  {
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIXHWK_CTRL_NODE_MESSAGE_PIXHAWK_STEERINGCONTROL_H
