// Generated by gencpp from file pixhwk_ctrl_node/traffic_light.msg
// DO NOT EDIT!


#ifndef PIXHWK_CTRL_NODE_MESSAGE_TRAFFIC_LIGHT_H
#define PIXHWK_CTRL_NODE_MESSAGE_TRAFFIC_LIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pixhwk_ctrl_node
{
template <class ContainerAllocator>
struct traffic_light_
{
  typedef traffic_light_<ContainerAllocator> Type;

  traffic_light_()
    : header()
    , dist_light(0.0)
    , color_light()  {
    }
  traffic_light_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dist_light(0.0)
    , color_light(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _dist_light_type;
  _dist_light_type dist_light;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_light_type;
  _color_light_type color_light;





  typedef boost::shared_ptr< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> const> ConstPtr;

}; // struct traffic_light_

typedef ::pixhwk_ctrl_node::traffic_light_<std::allocator<void> > traffic_light;

typedef boost::shared_ptr< ::pixhwk_ctrl_node::traffic_light > traffic_lightPtr;
typedef boost::shared_ptr< ::pixhwk_ctrl_node::traffic_light const> traffic_lightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pixhwk_ctrl_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pixhwk_ctrl_node': ['/home/deepak/catkin_ws/src/PixHawkController/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8df0c506b0f4a93a3c764f8dfe78ca5";
  }

  static const char* value(const ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8df0c506b0f4a93ULL;
  static const uint64_t static_value2 = 0xa3c764f8dfe78ca5ULL;
};

template<class ContainerAllocator>
struct DataType< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pixhwk_ctrl_node/traffic_light";
  }

  static const char* value(const ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 dist_light\n\
string color_light\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dist_light);
      stream.next(m.color_light);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct traffic_light_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pixhwk_ctrl_node::traffic_light_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dist_light: ";
    Printer<double>::stream(s, indent + "  ", v.dist_light);
    s << indent << "color_light: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color_light);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIXHWK_CTRL_NODE_MESSAGE_TRAFFIC_LIGHT_H
